### ISSUE TITLE
chronic-treatment-chart - Support for Drug-O-Gram in Bahmni gauge commons

### ISSUE THREAD

**Issue by bharatak** [Bahmni/bahmni-gauge#13]
The Drug-O-Gram looks like [this](http://picpaste.com/BsBzzMfL.png).  Create support for it bahmni-gauge-commons like this [ObsDisplayControl](https://github.com/Bahmni/bahmni-gauge/blob/master/bahmni-gauge-commons/src/main/java/org/bahmni/gauge/common/clinical/displaycontrol/ObsDisplayControl.java)

This class should accept WebElement as a constructor. It should expose the below methods

`Map<String, List<String>> getValues(){} - The key is the header column name and the List<String> are the values.
`

**Comment by SwathiVarkala** [comment]
Added support for DrugOGram with below commit. Closing the issue.
https://github.com/Bahmni/bahmni-gauge/commit/94639a7f0d95f6e14d59232b56fa98d8f093b6e9
