### ISSUE TITLE
Drug Orders: Support for Drug Order API in Bahmni gauge commons

### ISSUE THREAD

**Issue by bharatak** [Bahmni/bahmni-gauge#17]
Add support for adding multiple Drugs in one API call

1. Create a class called DrugOrder.  This class should support all the fields that are accepted by UI. 
2. Add the below method in BahmniRestClient
`createDrugOrders(List<DrugOrder> drugOrders) - Creates the drug orders using EMRAPI`
3. The spec should accept a table containing various fields required for creation of drug order.  This table should be able to accept multiple drug orders (i.e. multiple rows should be supported in the table).

**Comment by lipikadugar** [comment]
0c41851ba8db912925f93da2062b853d062e54ba
