### ISSUE TITLE
Treatment Tab - Support for UI automation of Treatment Tab

### ISSUE THREAD

**Issue by bharatak** [Bahmni/bahmni-gauge#19]
This story is linked to [17](https://github.com/Bahmni/bahmni-gauge/issues/17).

1. The DrugOrder class created in issue 17 should be used to fill up the Treatment tab. 
2. Create TreatmentPage class.  Add a method called createDrugOrder() to create a drug order
3. Add TreatmentPageSpec class.  This class should contain steps to accept a Table of DrugOrder.

**Comment by swarupkm** [comment]
Issue fixed with the following commits
a4825173fadd3dc745c891f981af0a3fefc91b00
0163be6da4324b40bb758db67f1e008e4a37b60c
0dea1eb0b864a67ff72c10ddd295558ec08bd7f0
