### ISSUE TITLE
Common: Support for inactivating the patients using API

### ISSUE THREAD

**Issue by bharatak** [Bahmni/bahmni-gauge#2]
We should be able to support inactivating the patients as part of TearDown step.  

- Create a method called retirePatient() in BahmniRestClient.  A REST call should be made to retire the patient by identifier.
- Create a step in RegistrationFirstPageSpec which takes the patient detail from the DataStore and invokes the above method
- Add this step in all the existing test specs

**Comment by lipikadugar** [comment]
Related Commits: 
153a85d63153cdf1e1908c3daf891b6c4fe1d317 Lipika| Added retiring patient after every scenario
077f1519dad1ff193cb4522411882cbfc9c3a3fe 	Lipika| Retiring a patient created through user interface
b5af9f9f37ba4b2797e6923158e93aed2047b45b Lipika| Retiring a patient created through API
