### ISSUE TITLE
endtb: Support for sanity tests of various users

### ISSUE THREAD

**Issue by bharatak** [Bahmni/bahmni-gauge#3]
Support for sanity tests in various environments.  Add the sanity tag to these testcases so that it can be run on multiple environments

- Ensure that msfuser1 is existing on the environment
- Ensure that pihuser1 is existing on the environment
- Ensure that irduser1 is existing on the environment

**Comment by priyankasahaisaxena** [comment]
Related Commits:
e3fe798 - Priyanka | #3 | Add test case for login validation of consortium users
5b5e491 - Priyanka| #3 | add wait time for login page in validation of consortium user IDs
f3d6fe5 - Priyanka| #3 | adding logout step in all test cases to ensure login page for next run
eeda0a4 - Priyanka| #3 | add timer for login page

**Comment by bharatak** [comment]
@priyankasahaisaxena 

- Can you add the tag regression so that it gets executed on QA box as well.  
- Line 17 has a small alignment issue (with the star) . Can you please correct it?
- Please ensure that it runs as part of the CI

**Comment by bharatak** [comment]
@priyankasahaisaxena Is this complete? If so, can you close this issue?
